=== SagePoint/sagepoint-docs/schemas/templates/survey_profile.json
{
     "type":"object",
     "$schema": "http://json-schema.org/draft-04/schema",
     "properties":{
          "bands": {
               "type":"number"
          },
          "cert": {
               "type":"number"
          },
          "confidence_bands": {
               "type":"number"
          },
          "corner_value_max": {
               "type":"number"
          },
          "corner_value_mid_1": {
               "type":"number"
          },
          "corner_value_mid_2": {
               "type":"number"
          },
          "corner_value_min": {
               "type":"number"
          },
          "curve_type": {
               "type":"number"
          },
          "history_duration_days": {
               "type":"number"
          },
          "id": {
               "type":"number"
          },
          "lfm_ts_distant": {
               "type":"number"
          },
          "lfm_ts_recent": {
               "type":"number"
          },
          "max_rating_value": {
               "type":"number"
          },
          "min_rating_value": {
               "type":"number"
          },
          "num_answers": {
               "type":"number"
          },
          "num_skill_levels": {
               "type":"number"
          },
          "pvalues": {
               "type":"string"
          },
          "resume_task_multiplier": {
               "type":"number"
          },
          "retention_rate": {
               "type":"number"
          },
          "skill_level_max": {
               "type":"number"
          },
          "skill_level_min": {
               "type":"number"
          },
          "skill_survey_score": {
               "type":"number"
          },
          "sum_coefficient": {
               "type":"number"
          },
          "time_slices": {
               "type":"number"
          },
          "uvalues": {
               "type":"string"
          },
          "version": {
               "type":"number"
          }
     }
}

=== SagePoint/sagepoint-docs/schemas/samples/survey_profile.json
{
     "id": 123,
     "version": 1,
     "skill_level_min": 800,
     "num_answers": 10,
     "curve_type": 3,
     "skill_level_max": 1000,
     "time_slices": 4,
     "retention_rate": 0.2,
     "cert": 1020,
     "corner_value_max": 100,
     "lfm_ts_recent": 10.5,
     "bands": 5,
     "corner_value_mid_1": 50,
     "lfm_ts_distant": 0.5,
     "confidence_bands": 5,
     "corner_value_mid_2": 5,
     "num_skill_levels": 5,
     "corner_value_min": 4,
     "max_rating_value": 740,
     "min_rating_value": 500,
     "skill_survey_score": 1,
     "resume_task_multiplier": 0.899,
     "history_duration_days": 65,
     "uvalues": "sdfsdfsdf sfsdfsdf----sdfdsf",
     "pvalues": "sdfsdfsdf sfsdfsdf----sdfdsf",
     "sum_coefficient": 1
}
